<?xml version="1.0"?>
<testsuites>
  <testsuite errors="0" failures="96" name="Elixir.Calculator.AdderTest" tests="154" time="0.0015">
    <properties>
      <property name="date" value="2021-01-25T16:38:21.578463Z" />
      <property name="seed" value="541556" />
    </properties>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 4 + 3 = 1 0.9269337563685592" time="0.0000">
      <failure message="Assertion with == failed">  1) test fails with 4 + 3 = 1 0.9269337563685592 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(4, 3) == 1
     left:  7
     right: 1
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 9 + 4 = 5 0.7425599122652476" time="0.0000">
      <failure message="Assertion with == failed">  2) test fails with 9 + 4 = 5 0.7425599122652476 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(9, 4) == 5
     left:  13
     right: 5
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 0 + 3 = -3 0.5550937740305246" time="0.0000">
      <failure message="Assertion with == failed">  3) test fails with 0 + 3 = -3 0.5550937740305246 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(0, 3) == -3
     left:  3
     right: -3
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 2 + 8 = 10 0.7214726116110991" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 9 + 4 = 7 0.40410696161116166" time="0.0000">
      <failure message="Assertion with == failed">  5) test fails with 9 + 4 = 7 0.40410696161116166 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(9, 4) == 7
     left:  13
     right: 7
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 4 + 7 = 3 0.7696636337231401" time="0.0000">
      <failure message="Assertion with == failed">  6) test fails with 4 + 7 = 3 0.7696636337231401 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(4, 7) == 3
     left:  11
     right: 3
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 4 + 9 = 13 0.12324249778231067" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 2 + 9 = 1 0.260885406570899" time="0.0000">
      <failure message="Assertion with == failed">  8) test fails with 2 + 9 = 1 0.260885406570899 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(2, 9) == 1
     left:  11
     right: 1
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 3 + 9 = 3 0.47228969885577443" time="0.0000">
      <failure message="Assertion with == failed">  9) test fails with 3 + 9 = 3 0.47228969885577443 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(3, 9) == 3
     left:  12
     right: 3
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 9 + 4 = 5 0.6689058912184951" time="0.0000">
      <failure message="Assertion with == failed"> 10) test fails with 9 + 4 = 5 0.6689058912184951 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(9, 4) == 5
     left:  13
     right: 5
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 0 + 2 = -2 0.7440076148464481" time="0.0000">
      <failure message="Assertion with == failed"> 11) test fails with 0 + 2 = -2 0.7440076148464481 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(0, 2) == -2
     left:  2
     right: -2
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 1 + 1 = 2 0.25303134491905" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 6 + 5 = 11 0.625296700759468" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 5 + 3 = 2 0.47574703033345145" time="0.0000">
      <failure message="Assertion with == failed"> 14) test fails with 5 + 3 = 2 0.47574703033345145 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(5, 3) == 2
     left:  8
     right: 2
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 1 + 4 = 5 0.6265902263461729" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 1 + 8 = 1 0.24881570738956182" time="0.0000">
      <failure message="Assertion with == failed"> 16) test fails with 1 + 8 = 1 0.24881570738956182 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(1, 8) == 1
     left:  9
     right: 1
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 9 + 3 = 4 0.3781626489178017" time="0.0000">
      <failure message="Assertion with == failed"> 17) test fails with 9 + 3 = 4 0.3781626489178017 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(9, 3) == 4
     left:  12
     right: 4
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 1 + 10 = 11 0.20978619158697087" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 8 + 9 = 15 0.846784067728539" time="0.0000">
      <failure message="Assertion with == failed"> 19) test fails with 8 + 9 = 15 0.846784067728539 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(8, 9) == 15
     left:  17
     right: 15
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 8 + 4 = 0 0.38771359762861746" time="0.0000">
      <failure message="Assertion with == failed"> 20) test fails with 8 + 4 = 0 0.38771359762861746 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(8, 4) == 0
     left:  12
     right: 0
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 3 + 0 = 1 0.9354854479427063" time="0.0000">
      <failure message="Assertion with == failed"> 21) test fails with 3 + 0 = 1 0.9354854479427063 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(3, 0) == 1
     left:  3
     right: 1
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 10 + 5 = 15 0.9546409473822649" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 9 + 2 = 9 0.8806807314683843" time="0.0000">
      <failure message="Assertion with == failed"> 23) test fails with 9 + 2 = 9 0.8806807314683843 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(9, 2) == 9
     left:  11
     right: 9
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 2 + 8 = 3 0.23671359103945888" time="0.0000">
      <failure message="Assertion with == failed"> 24) test fails with 2 + 8 = 3 0.23671359103945888 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(2, 8) == 3
     left:  10
     right: 3
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 3 + 8 = -5 0.5221487222915623" time="0.0000">
      <failure message="Assertion with == failed"> 25) test fails with 3 + 8 = -5 0.5221487222915623 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(3, 8) == -5
     left:  11
     right: -5
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 6 + 2 = 4 0.10201032170721658" time="0.0000">
      <failure message="Assertion with == failed"> 26) test fails with 6 + 2 = 4 0.10201032170721658 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(6, 2) == 4
     left:  8
     right: 4
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 1 + 5 = -4 0.16964198798120267" time="0.0000">
      <failure message="Assertion with == failed"> 27) test fails with 1 + 5 = -4 0.16964198798120267 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(1, 5) == -4
     left:  6
     right: -4
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 5 + 8 = 10 0.31510611173921454" time="0.0000">
      <failure message="Assertion with == failed"> 28) test fails with 5 + 8 = 10 0.31510611173921454 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(5, 8) == 10
     left:  13
     right: 10
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 8 + 2 = 6 0.6272486481317251" time="0.0000">
      <failure message="Assertion with == failed"> 29) test fails with 8 + 2 = 6 0.6272486481317251 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(8, 2) == 6
     left:  10
     right: 6
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 7 + 4 = 11 0.34490301686740743" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 3 + 5 = -2 0.7965032284444054" time="0.0000">
      <failure message="Assertion with == failed"> 31) test fails with 3 + 5 = -2 0.7965032284444054 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(3, 5) == -2
     left:  8
     right: -2
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 4 + 9 = 13 0.539665704382461" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 7 + 4 = 3 0.23271202727924012" time="0.0000">
      <failure message="Assertion with == failed"> 33) test fails with 7 + 4 = 3 0.23271202727924012 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(7, 4) == 3
     left:  11
     right: 3
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 6 + 3 = 3 0.11664550415837127" time="0.0000">
      <failure message="Assertion with == failed"> 34) test fails with 6 + 3 = 3 0.11664550415837127 (Calculator.AdderTest)
     test/calculator/adder_test.exs:15
     Assertion with == failed
     code:  assert Calculator.Adder.run(6, 3) == 3
     left:  9
     right: 3
     stacktrace:
       test/calculator/adder_test.exs:16: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 2 + 4 = 2 0.162160829474151" time="0.0000">
      <failure message="Assertion with == failed"> 35) test fails with 2 + 4 = 2 0.162160829474151 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(2, 4) == 2
     left:  6
     right: 2
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test succeeds with 9 + 9 = 18 0.5353285849096904" time="0.0000" />
    <testcase file="test/calculator/adder_test.exs" classname="Elixir.Calculator.AdderTest" name="test fails with 7 + 9 = 4 0.12696162846956116" time="0.0000">
      <failure message="Assertion with == failed"> 37) test fails with 7 + 9 = 4 0.12696162846956116 (Calculator.AdderTest)
     test/calculator/adder_test.exs:22
     Assertion with == failed
     code:  assert Calculator.Adder.run(7, 9) == 4
     left:  16
     right: 4
     stacktrace:
       test/calculator/adder_test.exs:23: (test)
</failure>
    </testcase>
  </testsuite>
</testsuites>